// ============================================================
// Phase E-3 用 Sprite データ
// HTML デモから TypeScript モジュールへ変換
// ============================================================

export type SpriteData = {
  grid: { w: number; h: number };
  pixelSize: number;       // 表示倍率
  frames: {
    walkA: string[];
    walkB: string[];
    blink: string[];
  };
  colors: Record<string, string>;
  animation: {
    frameInterval: number;  // フレーム切替周期(ms)
    moveSpeed: number;      // 1ステップあたり移動量(px)
    moveOnBFrame: boolean;  // walkB時にも移動するか(false=Aフレーム時のみ移動)
    blinkDuration: number;  // まばたき時間(ms)
    blinkIntervalMin: number; // まばたき間隔の最小(ms)
    blinkIntervalMax: number; // まばたき間隔の最大(ms)
  };
};

// ============================================================
// Monk-Baby (モンクのヒナ) — 24×24
// ============================================================
export const MONK_BABY: SpriteData = {
  grid: { w: 24, h: 24 },
  pixelSize: 4,
  colors: {
    O: '#3a2a1a',
    W: '#fdf6e3',
    s: '#e8dcc4',
    E: '#1a1a1a',
    B: '#e8871e',
    '.': 'transparent',
  },
  frames: {
    walkA: [
      '........................',
      '........................',
      '...........OOOO.........',
      '..........OWWWWO........',
      '..........OWWWWO........',
      '.........OOWWWWOO.......',
      '........OOWWWWWWOO......',
      '.......OWWWWWWWWWWO.....',
      '......OWWWWWWWWWWWWO....',
      '.....OWWWWWWWWWWWWWWO...',
      '.....OWWEEWWWWWWEEWWO...',
      '.....OWWEEWWWWWWEEWWO...',
      '....OWWWWWWWBBWWWWWWWO..',
      '....OWWWWWWWWWWWWWWWWO..',
      '....OWWWWWssssssWWWWWO..',
      '...OOWWWssssssssssWWWOO.',
      '...OWOWssssssssssssWOWO.',
      '....OWssssssssssssssWO..',
      '....OWWssssssssssssWWO..',
      '.....OWWWssssssssWWWO...',
      '......OWWWWWWWWWWWWO....',
      '.......OOOOOOOOOOOO.....',
      '......OOO........OO.....',
      '.....OOO.........OO.....',
    ],
    walkB: [
      '........................',
      '........................',
      '...........OOOO.........',
      '..........OWWWWO........',
      '..........OWWWWO........',
      '.........OOWWWWOO.......',
      '........OOWWWWWWOO......',
      '.......OWWWWWWWWWWO.....',
      '......OWWWWWWWWWWWWO....',
      '.....OWWWWWWWWWWWWWWO...',
      '.....OWWEEWWWWWWEEWWO...',
      '.....OWWEEWWWWWWEEWWO...',
      '....OWWWWWWWBBWWWWWWWO..',
      '....OWWWWWWWWWWWWWWWWO..',
      '....OWWWWWssssssWWWWWO..',
      '...OOWWWssssssssssWWWOO.',
      '...OWOWssssssssssssWOWO.',
      '....OWssssssssssssssWO..',
      '....OWWssssssssssssWWO..',
      '.....OWWWssssssssWWWO...',
      '......OWWWWWWWWWWWWO....',
      '.......OOOOOOOOOOOO.....',
      '........OO........OOO...',
      '........OO.........OOO..',
    ],
    blink: [
      '........................',
      '........................',
      '...........OOOO.........',
      '..........OWWWWO........',
      '..........OWWWWO........',
      '.........OOWWWWOO.......',
      '........OOWWWWWWOO......',
      '.......OWWWWWWWWWWO.....',
      '......OWWWWWWWWWWWWO....',
      '.....OWWWWWWWWWWWWWWO...',
      '.....OWWWWWWWWWWWWWWO...',
      '.....OWWEEEEWWEEEEWWO...',
      '....OWWWWWWWBBWWWWWWWO..',
      '....OWWWWWWWWWWWWWWWWO..',
      '....OWWWWWssssssWWWWWO..',
      '...OOWWWssssssssssWWWOO.',
      '...OWOWssssssssssssWOWO.',
      '....OWssssssssssssssWO..',
      '....OWWssssssssssssWWO..',
      '.....OWWWssssssssWWWO...',
      '......OWWWWWWWWWWWWO....',
      '.......OOOOOOOOOOOO.....',
      '......OOO........OO.....',
      '.....OOO.........OO.....',
    ],
  },
  animation: {
    frameInterval: 350,
    moveSpeed: 5,
    moveOnBFrame: true,
    blinkDuration: 150,
    blinkIntervalMin: 3000,
    blinkIntervalMax: 5000,
  },
};

// ============================================================
// Daraku-Monk (堕落僧) — 40×30
// ============================================================
export const DARAKU_MONK: SpriteData = {
  grid: { w: 40, h: 30 },
  pixelSize: 4,
  colors: {
    O: '#323c57',
    G: '#95b0c3',
    g: '#566b86',
    E: '#1a1c2b',
    M: '#5d265d',
    '.': 'transparent',
  },
  frames: {
    walkA: [
      '........................................',
      '........................................',
      '................................GG......',
      '...............................GggG.....',
      '..............................GGggG.....',
      '.................GGGG.........GgG.......',
      '...............ggggggGGG......GggG......',
      '.............GgGGGGGGgggG......Ggg......',
      '.............gGGGGGGGGGGggG....Ggg......',
      '............GGGGGGGGGGGGGgG...GgGG......',
      '...........GgGGGGGGGGGGGGGgG..GgG.......',
      '...........gGGGGGGGGGGGGGGGgG..GG.......',
      '..........ggGGGGGGGGGGGGGGGGg..G........',
      '.........GgGGGGGEEGGGGEEGGGGg...........',
      '.........GOGGGGGEEGGGGEEGGGGG...........',
      '.........GOGGGGGGGGGGGGGGGGGgG..........',
      '.........gMGGGGGGGGggGGGGGGGgg..........',
      '........GgggGGGGGGgOOGGGGGGggOg.........',
      '.......GgggOgGGGGGgggGGGGGGgggOG........',
      '......GgggggGgGGGGGGGGGGGGggGgOgG.......',
      '......GggOgggOgGGGGGGGGGGgOggOOgg.......',
      '......GgGOOOOOgGGGGGGGGGGgOOOOOgg.......',
      '......GgggOOOOgGGGGGGGGGGgOOOOggg..G....',
      '....GGGgggggOgGggggggggggGgOOggOg..g....',
      '...GgG.GgggOOGGgggggggggGGggOggg..GgG...',
      '..Gggg.GOOOOEgggOggggggggggOOOOgGggggG..',
      '...GGG..GGgggEOEOOOggggOOEOggGG...GGG...',
      '..............GGGGGGGGGGGG..............',
      '........................................',
      '........................................',
    ],
    walkB: [
      '........................................',
      '........................................',
      '........................................',
      '................................GG......',
      '...............................GggG.....',
      '..............................GGggG.....',
      '.................GGGG.........GgG.......',
      '...............ggggggGGG......GggG......',
      '.............GgGGGGGGgggG......Ggg......',
      '.............gGGGGGGGGGGggG....Ggg......',
      '............GGGGGGGGGGGGGgG...GgGG......',
      '...........GgGGGGGGGGGGGGGgG..GgG.......',
      '...........gGGGGGGGGGGGGGGGgG..GG.......',
      '..........ggGGGGGGGGGGGGGGGGg..G........',
      '.........GgGGGGGEEGGGGEEGGGGg...........',
      '.........GOGGGGGEEGGGGEEGGGGG...........',
      '.........GOGGGGGGGGGGGGGGGGGgG..........',
      '.........gMGGGGGGGGggGGGGGGGgg..........',
      '........GgggGGGGGGgOOGGGGGGggOg.........',
      '.......GgggOgGGGGGgggGGGGGGgggOG........',
      '......GgggggGgGGGGGGGGGGGGggGgOgG.......',
      '......GggOgggOgGGGGGGGGGGgOggOOgg.......',
      '......GgGOOOOOgGGGGGGGGGGgOOOOOgg.......',
      '......GgggOOOOgGGGGGGGGGGgOOOOggg..G....',
      '....GGGgggggOgGggggggggggGgOOggOg..g....',
      '...GgG.GgggOOGGgggggggggGGggOggg..GgG...',
      '..Gggg.GOOOOEgggOggggggggggOOOOgGggggG..',
      '...GGG..GGgggEOEOOOggggOOEOggGG...GGG...',
      '..............GGGGGGGGGGGG..............',
      '........................................',
    ],
    blink: [
      '........................................',
      '........................................',
      '................................GG......',
      '...............................GggG.....',
      '..............................GGggG.....',
      '.................GGGG.........GgG.......',
      '...............ggggggGGG......GggG......',
      '.............GgGGGGGGgggG......Ggg......',
      '.............gGGGGGGGGGGggG....Ggg......',
      '............GGGGGGGGGGGGGgG...GgGG......',
      '...........GgGGGGGGGGGGGGGgG..GgG.......',
      '...........gGGGGGGGGGGGGGGGgG..GG.......',
      '..........ggGGGGGGGGGGGGGGGGg..G........',
      '.........GgGGGGGGGGGGGGGGGGGg...........',
      '.........GOGGGGEEEEGGEEEEGGGG...........',
      '.........GOGGGGGGGGGGGGGGGGGgG..........',
      '.........gMGGGGGGGGggGGGGGGGgg..........',
      '........GgggGGGGGGgOOGGGGGGggOg.........',
      '.......GgggOgGGGGGgggGGGGGGgggOG........',
      '......GgggggGgGGGGGGGGGGGGggGgOgG.......',
      '......GggOgggOgGGGGGGGGGGgOggOOgg.......',
      '......GgGOOOOOgGGGGGGGGGGgOOOOOgg.......',
      '......GgggOOOOgGGGGGGGGGGgOOOOggg..G....',
      '....GGGgggggOgGggggggggggGgOOggOg..g....',
      '...GgG.GgggOOGGgggggggggGGggOggg..GgG...',
      '..Gggg.GOOOOEgggOggggggggggOOOOgGggggG..',
      '...GGG..GGgggEOEOOOggggOOEOggGG...GGG...',
      '..............GGGGGGGGGGGG..............',
      '........................................',
      '........................................',
    ],
  },
  animation: {
    frameInterval: 450,
    moveSpeed: 4,
    moveOnBFrame: false,  // 不調の表現:Aフレーム時のみ移動
    blinkDuration: 200,
    blinkIntervalMin: 2500,
    blinkIntervalMax: 4500,
  },
};

// ============================================================
// Slothchi-King (怠惰王) — 64×32
// ============================================================
export const SLOTHCHI_KING: SpriteData = {
  grid: { w: 64, h: 32 },
  pixelSize: 4,
  colors: {
    O: '#1a1c2b',
    G: '#a8f070',
    g: '#7ac050',
    R: '#b23e53',
    F: '#ef7d58',
    Y: '#ffcc76',
    P: '#5d265d',
    d: '#323c57',
    k: '#566b86',
    B: '#95b0c3',
    E: '#0f0f19',
    '.': 'transparent',
  },
  frames: {
    walkA: [
      '................................................................',
      '................................................................',
      '................................................................',
      '................................ORO.............................',
      '...............................OORR.............................',
      '.........................OOOO..RRRRO............BBB.............',
      '.........................OOOORBFFFRO.kB.........BBB.............',
      '.........................OORRRRFFFFFkROOBB......BBB.............',
      '.........................ORRRRFRRFYROROOFO......BB..............',
      '.........................ORFFFFRRFFRRRRROOB.....................',
      '....................OOOOOkkOOOOkkOORRRRROkOOOO......BBB.........',
      '...................OOFRPPGGYYGBBBGYGOOROBPRRRRO.....BBB.........',
      '...................ORPPkkGGGGBYGGGYGGFkdOPPPRROO....BB..........',
      '..................BRPPPGGBGBBGGGGBYGYGGPdPRRRRRO................',
      '..............BB.BORRdGGGGGBBGGGGYGGGBGFROPRRRROO...............',
      '...............B.BOPdkGGGEEBBGGGEEGGGGGFROPPRRPPOO..............',
      '..............BB.BOdPGBGGEEGGGGGEEGGYGGFkOdPRRPPOO..............',
      '..............BOOPOORYFGYGGGGGGGGGBGGGGYBOOPPOOPOO..............',
      '...........BOOOOPdOPBGGYYGPPPkkGGYFGGGGYBkOBOOPPOOOOOOBB........',
      '..........OOORRPPPPFGGGGGGdPRddGGYYYGYYBBkBOddOPPOOOOkOB........',
      '.........OORRRRPdFOkGBGGGGdOOdGGGBGGGGBGBGkOOdOPRRRRRRRFBB......',
      '........OORRRRPPPkOOkBGGGGGGGGGGGBGGGGBYBGkOORdPRRRRRRRRkk......',
      '........BORRRPPPPkOOkOGGGGGGGGGGGBYGFGBYBGFkFRddRRRRRRRRkk......',
      '........BPPPPdddOOOGFkOkkBBGGGGGGGBGkGGYGGGOkkddPPPPPPPPOO......',
      '.....OOOPPOPOOOGGGFOkGOYYOGOOGGRROOkkOOOOOOOkkPPGGPPOOOOOO......',
      '....OOOORPdkOOBGGGFOGGOYYOOOOOGRRddkkOOOOOOkkkGGGGROOOOOOO......',
      '....ORRRRRdOOkkGBGBGOOOkkkRGGGFGGddOOOkFOOGYGGGGFFOOBBBBOOB.....',
      '....ORRRRRddPPOOkkkGGGGFFGGGGGGBBBBGFGBBYBBGGGkkkkOOBBBBkkkkk...',
      '.....kRRROOdkFkdOkGGkkkOOkkFFkkBBGFkkkkOkFGYGGdPPPFOOOkkkdPPPB..',
      '.....BOOOOkkddkkOYYGGPOOOOOOOOFkkkkkkOOOOOYGYGPdddYYkkkkkBdkB...',
      '........kkkkkkBBkOOBRkdkkddddkOOOOOOOOdkOBOBFFOOOOkRkkBBkkkB....',
      '.........BBBB..BkOdPdkB...BBBBBBBBBBBB...BOOOdkB..BBBB...BB.....',
    ],
    walkB: [
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................ORO..............B..............',
      '...............................OORR.............BkB.............',
      '.........................OOOO..RRRRO............kB..............',
      '.........................OOOORBFFFRO.kB.........................',
      '.........................OORRRRFFFFFkROOBB...........B..........',
      '.........................ORRRRFRRFYROROOFO..........Bk..........',
      '.........................ORFFFFRRFFRRRRROOB.....................',
      '....................OOOOOkkOOOOkkOORRRRROkOOOO.B................',
      '...................OOFRPPGGYYGBBBGYGOOROBPRRRROkB...............',
      '...................ORPPkkGGGGBYGGGYGGFkdOPPPRROO................',
      '..................BRPPPGGBGBBGGGGBYGYGGPdPRRRRRO................',
      '..............BB.BORRdGGGGGBBGGGGYGGGBGFROPRRRROO...............',
      '...............B.BOPdkGGGEEBBGGGEEGGGGGFROPPRRPPOO..............',
      '..............BB.BOdPGBGGEEGGGGGEEGGYGGFkOdPRRPPOO..............',
      '..............BOOPOORYFGYGGGGGGGGGBGGGGYBOOPPOOPOO..............',
      '...........BOOOOPdOPBGGYYGPPPkkGGYFGGGGYBkOBOOPPOOOOOOBB........',
      '..........OOORRPPPPFGGGGGGdPRddGGYYYGYYBBkBOddOPPOOOOkOB........',
      '.........OORRRRPdFOkGBGGGGdOOdGGGBGGGGBGBGkOOdOPRRRRRRRFBB......',
      '........OORRRRPPPkOOkBGGGGGGGGGGGBGGGGBYBGkOORdPRRRRRRRRkk......',
      '........BORRRPPPPkOOkOGGGGGGGGGGGBYGFGBYBGFkFRddRRRRRRRRkk......',
      '........BPPPPdddOOOGFkOkkBBGGGGGGGBGkGGYGGGOkkddPPPPPPPPOO......',
      '.....OOOPPOPOOOGGGFOkGOYYOGOOGGRROOkkOOOOOOOkkPPGGPPOOOOOO......',
      '....ORRRRRdOOkkGBGBGOOOkkkRGGGFGGddOOOkFOOGYGGGGFFOOBBBBOOB.....',
      '....ORRRRRddPPOOkkkGGGGFFGGGGGGBBBBGFGBBYBBGGGkkkkOOBBBBkkkkk...',
      '.....kRRROOdkFkdOkGGkkkOOkkFFkkBBGFkkkkOkFGYGGdPPPFOOOkkkdPPPB..',
      '.....BOOOOkkddkkOYYGGPOOOOOOOOFkkkkkkOOOOOYGYGPdddYYkkkkkBdkB...',
      '........kkkkkkBBkOOBRkdkkddddkOOOOOOOOdkOBOBFFOOOOkRkkBBkkkB....',
      '.........BBBB..BkOdPdkB...BBBBBBBBBBBB...BOOOdkB..BBBB...BB.....',
    ],
    blink: [
      '................................................................',
      '................................................................',
      '................................................................',
      '................................ORO.............................',
      '...............................OORR.............................',
      '.........................OOOO..RRRRO............BBB.............',
      '.........................OOOORBFFFRO.kB.........BBB.............',
      '.........................OORRRRFFFFFkROOBB......BBB.............',
      '.........................ORRRRFRRFYROROOFO......BB..............',
      '.........................ORFFFFRRFFRRRRROOB.....................',
      '....................OOOOOkkOOOOkkOORRRRROkOOOO......BBB.........',
      '...................OOFRPPGGYYGBBBGYGOOROBPRRRRO.....BBB.........',
      '...................ORPPkkGGGGBYGGGYGGFkdOPPPRROO....BB..........',
      '..................BRPPPGGBGBBGGGGBYGYGGPdPRRRRRO................',
      '..............BB.BORRdGGGGGBBGGGGYGGGBGFROPRRRROO...............',
      '...............B.BOPdkGGGGGBBGGGGGGGGGGFROPPRRPPOO..............',
      '..............BB.BOdPGBGEEEEGGGEEEEGYGGFkOdPRRPPOO..............',
      '..............BOOPOORYFGYGGGGGGGGGBGGGGYBOOPPOOPOO..............',
      '...........BOOOOPdOPBGGYYGPPPkkGGYFGGGGYBkOBOOPPOOOOOOBB........',
      '..........OOORRPPPPFGGGGGGdPRddGGYYYGYYBBkBOddOPPOOOOkOB........',
      '.........OORRRRPdFOkGBGGGGdOOdGGGBGGGGBGBGkOOdOPRRRRRRRFBB......',
      '........OORRRRPPPkOOkBGGGGGGGGGGGBGGGGBYBGkOORdPRRRRRRRRkk......',
      '........BORRRPPPPkOOkOGGGGGGGGGGGBYGFGBYBGFkFRddRRRRRRRRkk......',
      '........BPPPPdddOOOGFkOkkBBGGGGGGGBGkGGYGGGOkkddPPPPPPPPOO......',
      '.....OOOPPOPOOOGGGFOkGOYYOGOOGGRROOkkOOOOOOOkkPPGGPPOOOOOO......',
      '....OOOORPdkOOBGGGFOGGOYYOOOOOGRRddkkOOOOOOkkkGGGGROOOOOOO......',
      '....ORRRRRdOOkkGBGBGOOOkkkRGGGFGGddOOOkFOOGYGGGGFFOOBBBBOOB.....',
      '....ORRRRRddPPOOkkkGGGGFFGGGGGGBBBBGFGBBYBBGGGkkkkOOBBBBkkkkk...',
      '.....kRRROOdkFkdOkGGkkkOOkkFFkkBBGFkkkkOkFGYGGdPPPFOOOkkkdPPPB..',
      '.....BOOOOkkddkkOYYGGPOOOOOOOOFkkkkkkOOOOOYGYGPdddYYkkkkkBdkB...',
      '........kkkkkkBBkOOBRkdkkddddkOOOOOOOOdkOBOBFFOOOOkRkkBBkkkB....',
      '.........BBBB..BkOdPdkB...BBBBBBBBBBBB...BOOOdkB..BBBB...BB.....',
    ],
  },
  animation: {
    frameInterval: 500,
    moveSpeed: 4,
    moveOnBFrame: false,  // 怠惰の表現:Aフレーム時のみ移動
    blinkDuration: 300,
    blinkIntervalMin: 2500,
    blinkIntervalMax: 4500,
  },
};
